name: graphql_flutter
description: A GraphQL client for Flutter, bringing all the features from a modern GraphQL client to one easy to use package.
version: 1.0.0-alpha.6
authors:
  - Eus Dima <eus@zinoapp.com>
  - Zino Hofmann <zino@zinoapp.com>
homepage: https://github.com/zino-app/graphql-flutter/tree/next

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6
  http: ^0.11.3+17
  path_provider: ^0.4.1
  uuid: ^1.0.3
  graphql_parser: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0

environment:
  sdk: ">=2.0.0 <3.0.0"
